name: Deploy Laravel App to Hostinger

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Use the version that matches your Laravel app
          extensions: mbstring, xml, bcmath
          tools: composer

      - name: Install Dependencies
        run: |
          composer install --optimize-autoloader --no-dev
          npm install
          npm run build  # If you're using Vite

      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 45.84.205.136 # ${{ secrets.HOSTINGER_SSH_HOST }}
          username: u992745133 # ${{ secrets.HOSTINGER_SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"  # Copies the entire Laravel project
          target: "/home/u992745133/domains/ajdiafitnessgym.com/public_html"
          rm: true
          port: 65002
          debug: true
          command_timeout: 20m
          tar_exec: tar

      - name: Run SSH Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 45.84.205.136
          username: u992745133
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          script: |
            cd "/home/u992745133/domains/ajdiafitnessgym.com/public_html"

            # ✅ Create .env file with content
            cat <<EOT > .env
            APP_NAME='AJ DIA'
            APP_ENV=production
            APP_KEY=base64:JrxdwCI/yQs9QDql19kQtyh/Qqqx/ejpEiLtMQ9/mLE=
            APP_DEBUG=true
            APP_URL=https://ajdiafitnessgym.com
            LOG_CHANNEL=stack
            LOG_LEVEL=debug
            DB_CONNECTION=mysql
            DB_HOST=localhost
            DB_PORT=3306
            DB_DATABASE=u992745133_ajdiafitness
            DB_USERNAME=u992745133_ajdia
            DB_PASSWORD=">GGOCHs6C"
            BROADCAST_DRIVER=log
            CACHE_DRIVER=file
            FILESYSTEM_DISK=public
            QUEUE_CONNECTION=sync
            SESSION_DRIVER=file
            SESSION_LIFETIME=120
            MAIL_MAILER=smtp
            MAIL_HOST=smtp.hostinger.com
            MAIL_PORT=465
            MAIL_USERNAME="support@ajdiafitnessgym.com"
            MAIL_PASSWORD="Ajdia@2024"
            MAIL_ENCRYPTION=ssl
            MAIL_FROM_ADDRESS="support@ajdiafitnessgym.com"
            MAIL_FROM_NAME="AJ DIA"
            EOT

            # ✅ Install dependencies & run migrations & symlink storage
            composer2 install --optimize-autoloader --no-dev
            composer2 update fakerphp/faker

            php artisan key:generate
            php artisan storage:link
            php artisan migrate:fresh --seed --seeder=DatabaseSeeder --force

            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear

            # ✅ Load the admin panel to initialize dependencies
            # curl -k --show-error --output /dev/null https://ajdiafitnessgym.com/admin || true
            wget --no-check-certificate -qO- https://ajdiafitnessgym.com/admin > /dev/null || true

            # ✅ Copy .htaccess and index.php to parent folder
            cp public/.htaccess ./
            cp public/index2.php ./index.php
            cp -r public/build ./

            # ✅ Load the admin panel to initialize dependencies
            # wget --no-check-certificate -O- https://ajdiafitnessgym.com/admin

            # ✅ Copy folders to storage
            cp -r public/basset ./storage
            cp -r public/images ./storage/img
            cp public/img/trainer1.jpg ./storage/app/public/trainer1.jpg
            cp public/img/trainer2.jpg ./storage/app/public/trainer2.jpg
            cp public/img/trainer3.jpg ./storage/app/public/trainer3.jpg
